{% set name = "service_identity" %}
{% set version = "21.1.0" %}
{% set sha256 = "6e6c6086ca271dc11b033d17c3a8bea9f24ebff920c587da090afc9519419d34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed . --verbose

requirements:
  host:
    - python
    - pip
  run:
    - python
    - attrs >=16.0.0
    - pyasn1
    - pyasn1-modules
    - pyopenssl >=0.12

test:
  imports:
    - service_identity

about:
  home: https://github.com/pyca/service_identity
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Service identity verification for pyOpenSSL.
  description: |
    service_identity aspires to give you all the tools you need for verifying
    whether a certificate is valid for the intended purposes.
  doc_url: https://service-identity.readthedocs.io/en/stable/
  dev_url: https://github.com/pyca/service_identity

extra:
  recipe-maintainers:
    - isuruf
